"""add phone number

Revision ID: 803e219930c1
Revises: a7275d3252e6
Create Date: 2022-01-22 00:51:00.775967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803e219930c1'
down_revision = 'a7275d3252e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
